#!/bin/bash
# Install pyiron_aiflow 
tar -xzf pyiron_aiflow-ci.tar.gz
cd pyiron_aiflow-ci
pip install ./pyiron_ai ./pyiron_core ./pyiron_database ./pyiron_nodes ./pyironflow --no-deps --no-build-isolation
cd ..
rm -rf pyiron_aiflow-ci pyiron_aiflow-ci.tar.gz 

# Fix LLM Interface 
mv node_store.py /srv/conda/envs/notebook/lib/python3.12/site-packages/pyiron_ai

# Install Quantum Espresso Parser
cd qe_xml_parser
pip install . --no-deps --no-build-isolation
cd ..
rm -rf qe_xml_parser

# Install Jupyter Kernels 
mkdir -p /home/jovyan/.local/share/jupyter/kernels/flux
cp kernel_flux.json /home/jovyan/.local/share/jupyter/kernels/flux/kernel.json
mkdir -p /home/jovyan/.local/share/jupyter/kernels/pyiron
cp kernel_pyiron.json /home/jovyan/.local/share/jupyter/kernels/pyiron/kernel.json
rm kernel_flux.json kernel_pyiron.json 

# Clean up 
rm postBuild README.md environment.yml _config.yml _toc.yml CITATION.cff 


_config.yml			img
_toc.yml			kernel_flux.json
01_introduction.ipynb		kernel_pyiron.json
02_assyst.ipynb			kernel.json
02_pythoninterface.ipynb	node_store.py
03_fitting.ipynb		postBuild
03_quantumespresso.ipynb	potentials
04_validation.ipynb		pyiron_aiflow-ci.tar.gz
05_thermodynamics.ipynb		pyiron_core_data
CITATION.cff			pyiron_node_catalog.json
data				pyiron_nodes
environment.yml			qe_xml_parser
espresso			README.md
