#!/bin/bash
git clone https://github.com/pyiron/pyiron_core.git
cd pyiron_core
rm -r pyiron_core/pyiron_nodes
mv ../pyiron_nodes pyiron_core
pip install . --no-deps --no-build-isolation
cd ..

# Now clean up everything else
rm -r .github pyiron_core
rm _config.yml _toc.yml README.md environment.yml CITATION.cff postBuild